### ISSUE TITLE
Issue while SSH with RSA key.

### ISSUE THREAD

**Issue by ios3Dev** [x2on/libssh2-for-iOS#32]
I am using latest version of libssh2 (1.4.3) and I have build it with "libgcrypt" as per script "build-all.sh". Now it's all working fine but I am getting one issue with this is When I try to SSH with my server using RSA key it fails to authenticate and returns -18(LIBSSH2_ERROR_AUTHENTICATION_FAILED) in function "libssh2_userauth_publickey_fromfile(session, username, publickey, privatekey, passphrase)". 
Not sure What's wrong with new version of library? As Same thing working fine with the older version 1.4.2. But I had to update with latest one to make arm64 compatible.

USing this method with para to check authenticate status
libssh2_userauth_publickey_fromfile(session, username, pubkey,privatekey ,password);

Below is detail how I m gettig para
const char *pubkey= [_publicKey cStringUsingEncoding:NSUTF8StringEncoding];
const char *privatekey= [_privateKey cStringUsingEncoding:NSUTF8StringEncoding];
password=NULL
const char* username = [username1 cStringUsingEncoding:NSUTF8StringEncoding];
const char* password = [passWd cStringUsingEncoding:NSUTF8StringEncoding];

**Comment by x2on** [comment]
I think this is a problem in your implementation or a change in 1.4.3 (see changelog: http://www.libssh2.org/changes.html)
