### ISSUE TITLE
Library Version updates

### ISSUE THREAD

**Issue by carloscabanero** [x2on/libssh2-for-iOS#33]
Just a quick note to save someone a few mins. When building the library I noticed that openssl was not downloading (opensslv.h and other headers were missing). Version .d is not available anymore and I had to update to version e.

Also, we are running on libssh2.1.4.3, they are currently on 1.6. Is that correct and stable?

Thanks!!

**Comment by x2on** [comment]
Thanks for the hint - i updated the openssl submodule.
I currently don't get 1.6 build - but feel free to make a PR for this.
